global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django-backend'
    # The 'backend' hostname is available because docker-compose creates a network
    # for all services defined in the file.
    static_configs:
      - targets: ['web:8000']
